version: "3.1"
services:
  node:
    image: node:latest
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./_nodejs:/home/node/app
    expose:
      - "8081"
    command: "npm start"